### ISSUE TITLE
Try to run "python setup.py build_ext --inplace" in Windows 10

### ISSUE THREAD

**Issue by Cibi075** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#107]
C:\Users\Downloads\Compressed\R2CNN_Faster-RCNN_Tensorflow-master\libs\box_utils>python setup.py build_ext --inplace
running build_ext
Traceback (most recent call last):
  File "setup.py", line 132, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "C:\Users\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\slcib\Anaconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "setup.py", line 104, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup.py", line 77, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/issues/50

**Comment by yangxue0827** [comment]
You can refer to this script, which was modified by others before, and it is not guaranteed to be used directly. @Cibi075 
[setup.txt](https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow/files/4607435/setup.txt)

**Comment by nothingws** [comment]
> C:\Users\Downloads\Compressed\R2CNN_Faster-RCNN_Tensorflow-master\libs\box_utils>python setup.py build_ext --inplace
> running build_ext
> Traceback (most recent call last):
> File "setup.py", line 132, in 
> cmdclass={'build_ext': custom_build_ext},
> File "C:\Users\Anaconda3\lib\distutils\core.py", line 148, in setup
> dist.run_commands()
> File "C:\Users\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
> self.run_command(cmd)
> File "C:\Users\Anaconda3\lib\distutils\dist.py", line 985, in run_command
> cmd_obj.run()
> File "C:\Users\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
> _build_ext.build_ext.run(self)
> File "C:\Users\slcib\Anaconda3\lib\distutils\command\build_ext.py", line 340, in run
> self.build_extensions()
> File "setup.py", line 104, in build_extensions
> customize_compiler_for_nvcc(self.compiler)
> File "setup.py", line 77, in customize_compiler_for_nvcc
> default_compiler_so = self.compiler_so
> AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'

Have you solved the problem
