### ISSUE TITLE
关于训练结果的问题

### ISSUE THREAD

**Issue by dexterod** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#114]
您好楼主！

我想问一下，我使用咱们R2CNN程序和训练好的权重文件108000.ckpt，在DOTA的val上跑结果。最终显示mAP只有0.38。然后各种调参数，重新从头训练到50w次了，mAP最多也只到0.48。同样的问题还有RRPN。
有点想不通这精度的差距能差在哪里，会跟机器和配置啥有关吗？还是我有什么地方没有注意到么？

望大哥解惑，谢谢了~~

**Comment by yangxue0827** [comment]
建议使用[RetinaNet_Tensorflow_Rotation](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation)，里面包含了R2CNN-FPN的代码，基于Resnet50的baseline有72+

**Comment by dexterod** [comment]
> 建议使用[RetinaNet_Tensorflow_Rotation](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation)，里面包含了R2CNN-FPN的代码，基于Resnet50的baseline有72+

**Comment by dexterod** [comment]
嗯嗯，你的那篇文章我也拜读过了，非常棒，给了我很多启发。但是现在实验得与其他的一些基准算法做比较，我就想用你的这个R2CNN作为标准。所以你测下来60%的精度当时是加了FPN结构是么

**Comment by yangxue0827** [comment]
我推荐你的只是一个benchmark，里面基本都是baseline的方法，没有tricks。整个benchmark做过代码结构整理和优化，当前这个repo只有60+存在很多不完善的地方，所以基本已经不维护了。

**Comment by dexterod** [comment]
嗯嗯，好的，那我试试新方法吧，谢谢你~
