### ISSUE TITLE
How to train pre-trained model on Imagenet and adapt it to this model by myself?

### ISSUE THREAD

**Issue by ZhangGongjie** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#20]
May I ask how to train pre-trained model on Imagenet and adapt it to this model by myself?

Thank you so much

**Comment by yangxue0827** [comment]
Pre-training weights are provided here， which is trained by imagenet. @ @ZhangGongjie

**Comment by ZhangGongjie** [comment]
May I have the source of the pretrained model on imagenet? Where are they from?

**Comment by yangxue0827** [comment]
see readme.
![image](https://user-images.githubusercontent.com/29257168/49275783-6970e900-f4b7-11e8-8166-4ae3ad203868.png)
@ZhangGongjie
