### ISSUE TITLE
tfrecord error

### ISSUE THREAD

**Issue by heping0228** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#27]
I ues the convert_data_to_tfrecord.py to transform the cliped data to tfrecord,the code shows complete,but the tfrecord file size is zero,and  the path is right,what's the problem maybe?

**Comment by haibucuo0** [comment]
> I ues the convert_data_to_tfrecord.py to transform the cliped data to tfrecord,the code shows complete,but the tfrecord file size is zero,and the path is right,what's the problem maybe?

Hi,have you solved it? I got the same problem.

**Comment by qq497841592** [comment]
Hi,have you solved it? I got the same problem.

**Comment by haibucuo0** [comment]
我的还是路径问题，好好调试下
