### ISSUE TITLE
no CUDA-capable device is detected

### ISSUE THREAD

**Issue by heping0228** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#28]
when I python  train.py ,it shows no CUDA-capable device is detected ,but my cuda version is right,who get and solve this problem?

**Comment by yangxue0827** [comment]
Setting GPU id [here](https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow/blob/master/libs/configs/cfgs.py#L15) @heping0228
