### ISSUE TITLE
没有train.py

### ISSUE THREAD

**Issue by gbyy422990** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#3]
您好，非常感谢您的贡献，我看了readme但是没发现有train的脚本，不知道您方便上传一下吗？

**Comment by destinyzs** [comment]
can't find python.py

**Comment by mensaochun** [comment]
When will upload the train.py script?

**Comment by banderlog** [comment]
` find -iname *train*` from projects root dir shows no `train.py` script

**Comment by yangxue0827** [comment]
train.py script is upload. @gbyy422990 @liangzz1991 @mensaochun @banderlog
