### ISSUE TITLE
what does PIXEL_MEAN mean?

### ISSUE THREAD

**Issue by yanzistudio** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#30]
Hi @yangxue0827,  thank you and your team making this repository. Really appreciate it.
I am trying to read your code and confused about the meaning of PIXEL_MEAN. It was set to [123.68, 116.779, 103.939]. May I ask how you calculate these values and if we use our own dataset, do we need to calculate and update them?
I am trying to use my own dataset and it was contained by a group of gray images. I think the value of pixel_mean will influence a lot to its performance. Thank you in advance!

**Comment by yangxue0827** [comment]
Subtracting the mean value [103.939, 116.779, 123.68] can centralize all dimensions of the input data and speed up training. Besides, the mean value [103.939, 116.779, 123.68] comes from ImageNet, you can use your own mean value of your data, it does not affect performance. @yanzistudio
