### ISSUE TITLE
demo_rh.py

### ISSUE THREAD

**Issue by heping0228** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#31]
I python demo_rh.py , it shows the weight is 0,but I have put the trained weights file on the right place,what's the problem,,,  It doesn't like this initially...

**Comment by clw5180** [comment]
> I python demo_rh.py , it shows the weight is 0,but I have put the trained weights file on the right place,what's the problem,,, It doesn't like this initially...

also have weight = 0, what is the reason ?
