### ISSUE TITLE
怎么在自己的数据集里标注得到斜框的groundtruth

### ISSUE THREAD

**Issue by huishaoli** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#32]
请问怎么在自己的数据集里标注得到斜框的groundtruth?

**Comment by yangxue0827** [comment]
可以试试用[这个](https://github.com/wkentaro/labelme) @huishaoli

**Comment by pascal1129** [comment]
> 可以试试用[这个](https://github.com/wkentaro/labelme) @huishaoli

labelme标注得到的似乎时一个多边形（Polygon），如果想要得到旋转的矩形框是不是还需要自行对标注作进一步处理？
