### ISSUE TITLE
multi_gpu_train.py  error

### ISSUE THREAD

**Issue by 595972434** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#33]
Hi, i want to speed up the experiment by using multi_gpu_train.py.However,there are some errors:
     TypeError: build_whole_detection_network() got an unexpected keyword argument 'gtboxes_batch'!!!
     In line 46 of  multi_gpu_train.py,the function of build_whole_detection_network have 2 inputs and return 4 outputs.But in line 387 of build_whole_detection_network.py, this function have 3 inputs and return 7 outputs,and there is no input named gtboxes_batch.
     I have found  the similar question in your github: https://github.com/DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow/issues/5  .
     So how can i change the code? Thanks!!!

**Comment by yangxue0827** [comment]
this script is not work. @595972434
