### ISSUE TITLE
eval.py error 

### ISSUE THREAD

**Issue by heping0228** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#34]
when I use the eval.py ,it throws 

/media/heping/D/new/DOTA_MODEL/R2CNN_Faster-RCNN_Tensorflow-master/libs/val_libs/voc_eval_r.py:240: RuntimeWarning: invalid value encountered in true_divide
  rec = tp / int(num_pos)
mAP is : nan

my image_dir is the results obtained from the demo_rh.py,test_annotation_path is the corresponding annotation. Is there any problem? Thank you. @yangxue0827 

and the generated txt document：
P0003_0000_0000 0.980 599.5 273.6 26.5 108.3 -9.1
what"s the meaning of the last item? Is it h?

**Comment by VV4yne** [comment]
How do you sovle the question? I have the same now.
