### ISSUE TITLE
mAP of 0.39 on DOTA validation set

### ISSUE THREAD

**Issue by heping0228** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#35]
Using the provided trained-weights R2CNN and config files, I am getting 0.39 mAP on validation set of DOTA. it's right?   @yangJirui @yangxue0827

**Comment by yangxue0827** [comment]
This code has 60+ mAP. @heping0228

**Comment by heping0228** [comment]
how to get the merged result from the croped result. @yangxue0827
