### ISSUE TITLE
questions about the required annotation format 

### ISSUE THREAD

**Issue by omerbrandis** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#41]
Hello, 

Could you please provide additional information regarding training this network.
Specifically, I did not understand what is the required annotation format.

the instructions hint that Voc-pascal can/must be converted using convert_data_to_tfrecord.py
but I both :

a. do not understand this  - as far as i can tell, voc supports bounding box annotation of the form minx miny maxx maxy , i.e. using only 2 points of data -> rectangle only.
while in order to support/describe the object's pose/orientation we need 4 data points (quadrilateral bounding boxes)...    

b. was not able to do this - running convert_data_to_tfrecord.py on a valid voc xml file resulted in the following msg " Conversion is complete! " , yet the resulting file was empty.

c. could you suggest a suitable annotation tool ? 
or simply state the one that you have used ?

Thanks,
Omer.

**Comment by yangxue0827** [comment]
Refer to [here](https://github.com/yangxue0827/R2CNN_FPN_Tensorflow/blob/master/sample.xml). @omerbrandis

**Comment by yangxue0827** [comment]
[annotation    @@@tool](https://github.com/yangxue0827/labelme) @omerbrandis

**Comment by omerbrandis** [comment]
thank you Yangxue0827 for the quick reply,
But I'm afraid I still don't understand:

1. the example shows an xml file,
while the output of labelme is a json file.
can you please explain how you performed the conversion between formats ?

2. I have executed convert_data_to_tfrecord.py on an (manually edited) xml file that matches the example provided, 
received the following output " Conversion is complete! " , 
yet the resulting tfrecord file was empty.

Thanks,
Omer.
