### ISSUE TITLE
OutOfRange

### ISSUE THREAD

**Issue by Watrix-Fanchao** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#42]

**Comment by Watrix-Fanchao** [comment]
Yes, I solved it, thank you so much. but another question is that I run the code on DOTA_clip dataset with one GPU(TITAN V, BN freezed)and also evaluate it on clipped set, I found mAP just 51.04, so far from 60.67 you reported at 'Comparison'. Could you tell me why?

**Comment by yangxue0827** [comment]
Can you show me the results of each class? @Watrix-Fanchao

**Comment by Watrix-Fanchao** [comment]
horizon eval:
Writing roundabout VOC resutls file
Writing tennis-court VOC resutls file
Writing swimming-pool VOC resutls file
Writing storage-tank VOC resutls file
Writing soccer-ball-field VOC resutls file
Writing small-vehicle VOC resutls file
Writing ship VOC resutls file
Writing plane VOC resutls file
Writing large-vehicle VOC resutls file
Writing helicopter VOC resutls file
Writing harbor VOC resutls file
Writing ground-track-field VOC resutls file
Writing bridge VOC resutls file
Writing basketball-court VOC resutls file
Writing baseball-diamond VOC resutls file
cls : roundabout|| Recall: 0.5755395683453237 || Precison: 0.625|| AP: 0.510149202605173
cls : tennis-court|| Recall: 0.7837573385518591 || Precison: 0.9423529411764706|| AP: 0.7815579622397963
cls : swimming-pool|| Recall: 0.5405679513184585 || Precison: 0.662111801242236|| AP: 0.4488757781043197
cls : storage-tank|| Recall: 0.5182032477737035 || Precison: 0.8016612641815235|| AP: 0.5003088775225889
cls : soccer-ball-field|| Recall: 0.44717444717444715 || Precison: 0.5986842105263158|| AP: 0.3686044558881283
cls : small-vehicle|| Recall: 0.4544817381823846 || Precison: 0.6522127849798838|| AP: 0.36628102239844307
cls : ship|| Recall: 0.542250820300848 || Precison: 0.8188545688545689|| AP: 0.508245277361193
cls : plane|| Recall: 0.7583345904359632 || Precison: 0.8858149779735682|| AP: 0.7443337249039779
cls : large-vehicle|| Recall: 0.4152527700831025 || Precison: 0.7610661589719181|| AP: 0.3803626253653653
cls : helicopter|| Recall: 0.5153061224489796 || Precison: 0.5738636363636364|| AP: 0.4422144128013308
cls : harbor|| Recall: 0.6514066049274856 || Precison: 0.7184428598959337|| AP: 0.5981447928704284
cls : ground-track-field|| Recall: 0.6231155778894473 || Precison: 0.6966292134831461|| AP: 0.5586147157759185
cls : bridge|| Recall: 0.4180929095354523 || Precison: 0.5388655462184874|| AP: 0.33026323163663485
cls : basketball-court|| Recall: 0.42209631728045327 || Precison: 0.6506550218340611|| AP: 0.3729754918834921
cls : baseball-diamond|| Recall: 0.7272727272727273 || Precison: 0.7610993657505285|| AP: 0.6684534736419585
mAP is : 0.5052923363332499

**Comment by Watrix-Fanchao** [comment]
Oh, I found that I have omitted a detail that I stopped the training at 30W step.

**Comment by yangxue0827** [comment]
60 mAP is obtained by submitting the test data set to the [official system](http://captain.whu.edu.cn/DOTAweb/evaluation.html). @Watrix-Fanchao
