### ISSUE TITLE
算法上斜框生成的请教

### ISSUE THREAD

**Issue by HelloWorld19930113** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#43]
你好，想请教一下大佬的代码，是不是在水平框里去找的roi的最小矩形框？

**Comment by HelloWorld19930113** [comment]
谢谢大佬，大佬，看了一下代码，关于那个旋转角度，没看到在哪里计算的，只看通过一个求全连接层返回一个五维的数组

**Comment by yangxue0827** [comment]
函数都在libs/box_utils @HelloWorld19930113

**Comment by HelloWorld19930113** [comment]
你好大佬，我想请教一下跟换mobilenetv2得通道系数1.0.,1.4,可以跟换为0.5,0.75怎么会出现通道不匹配的错误？
