### ISSUE TITLE
question regarding input image resize

### ISSUE THREAD

**Issue by omerbrandis** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#44]
hello,

could you please shed some light on the input image resize that's performed in read_tfrecord.py-read_and_prepocess_single_img-image_preprocess.short_side_resize.

firstly can you please explain why this is done ?

additionally, can you also please explain why you have provided the default value of cfg.py: IMG_SHORT_SIDE_LEN = 800

Thanks,
Omer

**Comment by yangxue0827** [comment]
Preventing an image from being too large causes an OOM error. When training the DOTA dataset, the size of the image crop is 800. @omerbrandis

**Comment by omerbrandis** [comment]
Thank you very much for repling and trying to help.

But i still dont fully understand,
Since in my case the size of the input img is smaller 1280x720, thus the
resize enlarges it to 1422x800 , seems to have achived the exact opposite
of what was intended, is then a bug ?

Thanks.
Omer.

**Comment by yangxue0827** [comment]
This parameter is not fixed and needs to be adjusted according to your data set. @omerbrandis

**Comment by omerbrandis** [comment]
:-)

in other words, disregarding the memory consumption issue ( i could train
on a cpu with 64g of ram...),
This net can recieve an input image of any size and aspect ratio without
affecting the quality of the results ?

Omer.

**Comment by yangxue0827** [comment]
Yes

**Comment by omerbrandis** [comment]
Thanks again.

Can you please shed some light on how this is achived ?
( in my limited experience ive only seen nets that support  a set/fixed
input image size + i've seen that resnet itself expects a rectangle image +
mustn't/shouldn't other net parms like stride and sample size be adjusted
for images of different size ?)

+Must the image size used in training match that used in inference ?

**Comment by yangxue0827** [comment]
Not necessary @omerbrandis
