### ISSUE TITLE
reference_theta計算問題

### ISSUE THREAD

**Issue by issuetodd** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#47]
I saw your code and find
reference_theta = np.ones(reference_xmin.shape) * -90
I don't understand the relationship between reference_theta  and reference_xmin.
Can you explain what does this mean? Thanks a lot!

**Comment by yangxue0827** [comment]
they have the same shape. @issuetodd

**Comment by issuetodd** [comment]
Thanks for quick reply!
