### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError: exceptions.AttributeError: 'module' object has no attribute 'boxPoints'

### ISSUE THREAD

**Issue by fujingling** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#50]
您好，我加载完模型以后遇到一个这样的问题，看起来不是OpenCV的问题，您知道是哪里的问题吗？
![image](https://user-images.githubusercontent.com/27276823/53854847-063aa980-4006-11e9-94cc-118405ff7c7f.png)

**Comment by yangxue0827** [comment]
你opencv版本不对 @fujingling

**Comment by fujingling** [comment]
多谢@yangxue0827，我把OpenCV从2.7换成3.4.1就没报这个错了。
