### ISSUE TITLE
OutOfRangeError错误

### ISSUE THREAD

**Issue by wizholy** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#53]
训练集尺寸均为1000×800，出错。
OutOfRangeError (see above for traceback): PaddingFIFOQueue '_2_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

**Comment by wizholy** [comment]
tfrecord制作的问题，制作的时候要小心，一定要和作者的制作一模一样。

**Comment by xiangzhang06** [comment]
I had the same problem. How did you solve it? @wizholy
