### ISSUE TITLE
issue about data preparation

### ISSUE THREAD

**Issue by gxwangupc** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#54]
How to get this data format?

3、data format

├── VOCdevkit
│ ├── VOCdevkit_train
│ ├── Annotation
│ ├── JPEGImages
│ ├── VOCdevkit_test
│ ├── Annotation
│ ├── JPEGImages

**Comment by yangxue0827** [comment]
Need your own organization @gxwangupc

**Comment by gxwangupc** [comment]
> Need your own organization @gxwangupc
thank you
