### ISSUE TITLE
训练时间

### ISSUE THREAD

**Issue by ShoupingShan** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#55]
您好：
  我在代码中看到batchsize只能设为1，那么请问您在训练dota数据集大概花费了多长时间呢？大概迭代了多少次？非常感谢！

**Comment by yangxue0827** [comment]
30w，代码目前支持多gpu训练 @ShoupingShan

**Comment by yangxue0827** [comment]
参考[这里](https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/tools/multi_gpu_train.py) @ShoupingShan

**Comment by feufhd** [comment]
那原本的train不支持多gpu训练是吗，需要跑multi_gpu_train？
还有一个问题，如果在tfrecord文件夹中用不同的数据生成了多个tfrecord，如何训练指定的tfrecord？

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow/blob/master/data/io/read_tfrecord.py#L79  @feufhd

**Comment by feufhd** [comment]
直接改pattern路径就好了是吧！非常感谢！

**Comment by feufhd** [comment]
您好，我为什么看到的MAX_ITERATION是100w不是上面说的30w？

**Comment by yangxue0827** [comment]
30w就够了

**Comment by lilmangolil** [comment]
您好，请问楼主，训练自己的数据库，需要数据的标签也是倾斜有角度的吗？

**Comment by yangxue0827** [comment]
提供四个点的左边就行 @lilmangolil

**Comment by lilmangolil** [comment]
您好，请问比如我想训练FDDB人脸数据库，需要对其中的数据标签进行倾斜处理吗？还是说用原始的矩形标签就可以呢？

**Comment by yangxue0827** [comment]
你要跑通代码，只需要提供四个顶点的坐标就行，但是如果你标签是水平矩形框想结果是旋转的那是不行的 @lilmangolil

**Comment by lilmangolil** [comment]
谢谢回答，请问您是怎样训练人脸数据库的？是自己制作的标签吗？

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow/tree/master/data/io/FDDB  @ @lilmangolil

**Comment by zdgithub** [comment]
@yangxue0827  您好，我发现上面您提供的多gpu训练的代码是FPN网络的，请问R2CNN的多gpu训练代码multi_gpu_train是不是还没有完善，因为我发现我运行`python multi_gpu_train.py`会报错，而运行`python train.py`则可以正常训练

**Comment by yangxue0827** [comment]
这个repo多gpu我没有改，需要参考fpn的修改一下就行

**Comment by zdgithub** [comment]
哦哦，好的，多谢！

**Comment by baokelion** [comment]
> 哦哦，好的，多谢！

你好，请问多gpu的问题后来解决了吗？
