### ISSUE TITLE
关于eval的结果

### ISSUE THREAD

**Issue by feufhd** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#57]
我想问一下为什么我跑下载的trained_model却只得到40+的mAP结果？
我先跑了val_crop，然后加载了trained_model跑了eval，是哪个步骤有错吗？

**Comment by yangxue0827** [comment]
跑demo.py，然后结果提交官网评测系统 @feufhd

**Comment by feufhd** [comment]
谢谢回复！可是我想在验证集跑下结果看看

**Comment by yangxue0827** [comment]
那就用官网的评测代码 @feufhd

**Comment by feufhd** [comment]
我之前也想着用，可是官网的分割跟你的分割不太一样。。你的eval有结果合并的步骤嘛

**Comment by yangxue0827** [comment]
https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow/blob/master/tools/demo_rh.py @feufhd
