### ISSUE TITLE
预测出错

### ISSUE THREAD

**Issue by SuHaoXD** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#58]
用你训练好的的DOTA模型测试效果为什么是这样子？ 是需要修改哪里的cfg文件吗？
![P1385_r](https://user-images.githubusercontent.com/25171783/55288211-ba053e00-53e6-11e9-9ac1-b34c79d0b927.jpg)
![P1385_h](https://user-images.githubusercontent.com/25171783/55288220-c093b580-53e6-11e9-8e08-9ff3c71fac52.jpg)

**Comment by qq563604364** [comment]
使用的是DOTA cfg,  demo_rh.py预测，顺便想问一下预测为什么生成两张图片？一张r  一张h

**Comment by Smoothing97** [comment]
@SuHaoXD 同样的问题，我用了demo_rh.py，输入的图片是DOTA数据集里的val数据集，用val_crop.py切割成800*800，跑demo_rh.py也出现这样的情况。唯一一次出现大量正确标注的图片结果好像是因为我在demo_rh.py后又对这些图片结果跑了eval.py，绘制上去的box是gtbox....正在查到底哪里有问题。
PS：按照readme里写的应该是跑python inference.py --data_dir='/PATH/TO/DOTA/IMAGES_CROP/'  --gpu='0'来对crop好的图片做检测，但是我放置好weight文件跑这个还是出现你图中的结果，不知道为什么。如果你有什么建议或者看法，期待和我交流：）

**Comment by yangxue0827** [comment]
给一下你们checkpoint文件的绝对路径 @SuHaoXD @Smoothing97 可能是你们路径放的不对

**Comment by yangxue0827** [comment]
你们这个情况像是加载了pretrain weights

**Comment by SuHaoXD** [comment]
> 你们这个情况像是加载了pretrain weights

已解决，原因是模型未能正确加载。DOTA权重文件应该放在一个文件夹中，然后再将这个文件夹放在trained_weights中。 @Smoothing97   感谢作者分享！

**Comment by Smoothing97** [comment]
@SuHaoXD 我检查过这个问题，但是不太行，，我重新放置了一下，现在正在测试，过会儿回来更新：）
1、please download resnet50_v1、resnet101_v1 pre-trained models on Imagenet, put it to data/pretrained_weights.
![image](https://user-images.githubusercontent.com/32809975/56642960-3a982100-66ab-11e9-90f9-d6340f8b620b.png)
2、please download mobilenet_v2 pre-trained model on Imagenet, put it to data/pretrained_weights/mobilenet.
3、please download trained model by this project, put it to output/trained_weights.
![image](https://user-images.githubusercontent.com/32809975/56643189-b8f4c300-66ab-11e9-93d9-038146c32245.png)
![image](https://user-images.githubusercontent.com/32809975/56643212-c3af5800-66ab-11e9-8c9e-ea2841a36e41.png)

**Comment by Smoothing97** [comment]
更新回来了：我检查了一下cfgs.py里的VERSION = 'FasterRCNN_20180515_DOTA_v3'被我魔改成每天的日期了，可能找不到模型文件：）所以代码还是要好好看，随便改个什么就出BUG,233333
