### ISSUE TITLE
代码和文章里的不一致

### ISSUE THREAD

**Issue by destinyzs** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#6]
你好，repo的代码只是选取了resnet的最后一层作为特征，但是文章里说用了dense fpn的结构，请问这是为啥？没有开放嘛？
文章是Position Detection and Direction Prediction for Arbitrary-Oriented Ships via Multiscale Rotation Region Convolutional Neural Network @yangxue0827

**Comment by yangxue0827** [comment]
你好，这个只是最原始的基础代码，所有工作室基于这个改的，并不是文章里的代码。 @destinyzs

**Comment by destinyzs** [comment]
好的，非常感谢！那文章里的代码啥时候开源呢？我有些细节不是很清楚，想看看咋写的。

**Comment by yangxue0827** [comment]
https://github.com/yangxue0827/R-DFPN_FPN_Tensorflow    @destinyzs

**Comment by yangxue0827** [comment]
这个账号的代码都是新的，修改提升过的，效果有保证。给你的账号下的代码是最原始的，性能没有这里的好。 @destinyzs

**Comment by yangxue0827** [comment]
Position Detection and Direction Prediction主要是做舰船的方向预测，是一个maltitask，是rdfpn的功能扩展版本而已。 @destinyzs

**Comment by destinyzs** [comment]
好的，那我再去看看R-DFPN，感谢。

**Comment by yangxue0827** [comment]
后续基于R2CNN这个代码进行工作，但是主要针对的是DOTA数据集了。目前已经做了部分的改进和提升。

**Comment by destinyzs** [comment]
好的，我现在也是做的DOTA这个数据集，借鉴了R-DFPN的思路，但是效果没有它的好。

**Comment by yangxue0827** [comment]
因为之前基础代码复现的不好，所以目前rdfpn的代码并没有在dota取得较好的效果，还没有这个账号的r2cnn效果好。
