### ISSUE TITLE
draw_boxes_with_categories() got an unexpected keyword argument 'text'

### ISSUE THREAD

**Issue by Learningchen** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#60]
Traceback (most recent call last):
  File "multi_gpu_cy.py", line 227, in <module>    train()  File "multi_gpu_cy.py", line 143, in train
    fastrcnn_loc_loss, fastrcnn_cls_loss, fastrcnn_total_loss = tower_loss(scope)
  File "multi_gpu_cy.py", line 77, in tower_loss
    text=gtboxes_and_label[:, -1])
TypeError: draw_boxes_with_categories() got an unexpected keyword argument 'text'

您好，draw_boxes_with_categories()并没有text或者labels的参数，请问怎么修改？谢谢

**Comment by yangxue0827** [comment]
我没有提供这个multi_gpu_cy.py脚本吧 @Learningchen

**Comment by yangxue0827** [comment]
我没有提供这个multi_gpu_cy.py脚本吧 @Learningchen 
多gpu代码参看这个[脚本](https://github.com/DetectionTeamUCAS/FPN_Tensorflow/blob/master/tools/multi_gpu_train.py)修改一下就能使用，这个repo的多gpu我没有修改
