### ISSUE TITLE
如何测试&mAP=0.279的问题

### ISSUE THREAD

**Issue by Smoothing97** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#62]
@feufhd @yangxue0827 抱歉打扰了，我跑了val_crop将DOTA数据集分割，运行eval.py进行验证，但是出现了两个问题：
1.当我用demo_rh.py检测时，目视解译效果很不错，但是mAP效果不佳。旋转目标检测的结果如下:
`cls : baseball-diamond|| Recall: 0.3277027027027027 || Precison: 0.6799065420560748|| AP: 0.2857233511210732
mAP is : 0.27839696674514086
********************
rotation eval:
Writing roundabout VOC results file
Writing tennis-court VOC results file
Writing swimming-pool VOC results file
Writing storage-tank VOC results file
Writing soccer-ball-field VOC results file
Writing small-vehicle VOC results file
Writing ship VOC results file
Writing plane VOC results file
Writing large-vehicle VOC results file
Writing helicopter VOC results file
Writing harbor VOC results file
Writing ground-track-field VOC results file
Writing bridge VOC results file
Writing basketball-court VOC results file
Writing baseball-diamond VOC results file
cls : roundabout|| Recall: 0.05137844611528822 || Precison: 0.3942307692307692|| AP: 0.03896313329141163
cls : tennis-court|| Recall: 0.7942961165048543 || Precison: 0.9273822174991144|| AP: 0.7841216647894594
cls : swimming-pool|| Recall: 0.6034278959810875 || Precison: 0.4337298215802889|| AP: 0.4713228312417497
cls : storage-tank|| Recall: 0.08919098143236075 || Precison: 0.8359229334990678|| AP: 0.08359899690789072
cls : soccer-ball-field|| Recall: 0.4365482233502538 || Precison: 0.5|| AP: 0.37065461517016957
cls : small-vehicle|| Recall: 0.26025719534598896 || Precison: 0.44350029815146097|| AP: 0.14424862685392775
cls : ship|| Recall: 0.24484951836659447 || Precison: 0.7319509506751171|| AP: 0.20502145866938037
cls : plane|| Recall: 0.4970338303671637 || Precison: 0.8035251425609123|| AP: 0.47595213365825684
cls : large-vehicle|| Recall: 0.31162768312638367 || Precison: 0.6660152232051019|| AP: 0.23590015709743262
cls : helicopter|| Recall: 0.2857142857142857 || Precison: 0.42105263157894735|| AP: 0.2161832557262215
cls : harbor|| Recall: 0.1851032448377581 || Precison: 0.6090385198665453|| AP: 0.13665860486666898
cls : ground-track-field|| Recall: 0.4742268041237113 || Precison: 0.5302593659942363|| AP: 0.37650906662703715
cls : bridge|| Recall: 0.019583333333333335 || Precison: 0.27647058823529413|| AP: 0.006289862595004398
cls : basketball-court|| Recall: 0.37198795180722893 || Precison: 0.674863387978142|| AP: 0.33368834624831495
cls : baseball-diamond|| Recall: 0.3502252252252252 || Precison: 0.7300469483568075|| AP: 0.31682695380012843
mAP is : 0.2797293138362036
`
2.当我用demo.py检测时，得到的_r.jpg和_h.jpg效果很差，基本上没有有效的检测框被标注出来。
另外提到一点，我在运行val_crop.py后对验证集val分割得到的图片和标注文件不能够完全一一对应，经过文件名的筛选，有139张图片没有对应的标注文件，也有139个标注文件没有对应的图片。因此我将val/images和val/annotation两个文件夹的文件做了一一对应的检查，然后运行eval.py得到了上面的结果。
我会继续排查mAP与目视解译效果不匹配的问题，也希望有人能给我一些帮助，谢谢：）
一点猜想：可能是我的标注文件有问题，所以用看起来效果很好的检测结果去eval的时候，好的检测结果匹配到了不正确的gt而降低？？

**Comment by yangxue0827** [comment]
对于dota数据集建议用官方的评测脚本，eval.py之前只是对voc数据集进行使用过。 @Smoothing97

**Comment by Smoothing97** [comment]
@yangxue0827 谢谢回复！更新一下：用demo_rh.py评测了DOTA数据集的val数据集，修改了代码中的：
if save_res:
    生成含bbox标记的图片结果
#else:
generate_15_txt = True
if generate_15_txt:
    输出Task1_%s.txt，Task2_%s.txt..
然后运行一波demo_rh.py，定义好输出图片和txt的位置，得到结果了：）拿去dota_devkit里的评测脚本评价，但是得到的结果比github里公布的结果差几个点？
我加载了作者的网络和训练文件，在未经切割的原始val数据集上测试，共458张图片。
我的检测结果如下：
TASK1:

Approaches | mAP | PL | BD | BR | GTF | SV | LV | SH | TC | BC | ST | SBF | RA | HA | SP | HC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
R2CNN | 60.67 | 80.94 | 65.75 | 35.34 | 67.44 | 59.92 | 50.91 | 55.81 | 90.67 | 66.92 | 72.39 | 55.06 | 52.23 | 55.14 | 53.35 | 48.22
myR2CNN | 0.5401065416 | 81.08627798 | 60.87683514 | 26.29759713 | 50.97939969 | 33.29170672 | 43.51083627 | 44.24459943 | 81.17461554 | 49.84014248 | 69.28368385 | 63.16947305 | 54.25898275 | 55.53323254 | 50.7564373 | 45.85599253

可以看到
--飞机,soccer-ball-field类别高了一个点
--soccer-ball-field高了8个点
--roundabout,harbor,swimming-pool,helicopter基本不变或者掉了3个点
--small vehicle掉了27个点，ship,large vehicle,bridge掉了10个点左右（可能是小而密集的目标？）

TASK2:

myR2CNN | 0.5155691366 | 78.91565105 | 47.84596804 | 33.76335059 | 41.05487265 | 35.41112266 | 49.52863311 | 50.53492149 | 75.52822151 | 38.62538428 | 69.26705194 | 61.41086616 | 35.63223981 | 64.3559222 | 49.49917584 | 41.9803236
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

不知道为什么出现了很大的差异，正在探究中。。。

**Comment by pangzhan27** [comment]
Same problem as @Smoothing97 
Below is the result after stiching. if evaluated on cropped image, the result will be worse with map about 48. Any idea what may cause the variance of results, despite using the same trained model? (I use this trained model - FasterRCNN_20180515_DOTA_v3.rar - for evaluation)

mAP | PL | BD | BR | GTF | SV | LV | SH | TC | BC | ST | SBF | RA | HA | SP | HC
54.11 | 87.44 | 60.83 | 24.71 | 51.09 | 33.54 | 41.15 | 40.49 | 88.86 | 48.85 | 67.88 | 63.71 | 52.86 | 55.97 | 49.40 | 44.85

**Comment by czzbb** [comment]
请问下，demo_rh.py代码生成的tmp文件和output文件夹是用在官方测试代码的中变量detpath和imagesetfile的值对吗？另外annopath要怎么生成？

**Comment by yangxue0827** [comment]
- tmp是中间变量，作用是断点，防止程序意外中断可以续上；

- detpath是生成的测试结果文件，会放在output下对应的版本文件夹下；

- annopath当然是官方提供的标注文件。 @czzbb

**Comment by czzbb** [comment]
谢谢您！

**Comment by clw5180** [comment]
> Same problem as @Smoothing97
> Below is the result after stiching. if evaluated on cropped image, the result will be worse with map about 48. Any idea what may cause the variance of results, despite using the same trained model? (I use this trained model - FasterRCNN_20180515_DOTA_v3.rar - for evaluation)
> 
> mAP | PL | BD | BR | GTF | SV | LV | SH | TC | BC | ST | SBF | RA | HA | SP | HC
> 54.11 | 87.44 | 60.83 | 24.71 | 51.09 | 33.54 | 41.15 | 40.49 | 88.86 | 48.85 | 67.88 | 63.71 | 52.86 | 55.97 | 49.40 | 44.85

also get mAP = 0.48 on val_dataset. I don't change anything. Do you find the reason ?

**Comment by pangzhan27** [comment]
@clw5180 
I have retrained the model, and after about 9 epochs, i get map 58.4 after stiching on val_dataset, still a little lower than the reported one, yet closer. However, the author did not mention the metric of evaluation- whether it's on cropped images or original ones. If it's based on "DOTA: A Larger-scale Dataset for Object Detection in Aerial Images", the results would be on original images, which would make sense according to the re-implemented results.

**Comment by yangxue0827** [comment]
我列出来的结果是测试集的，通过提交系统得到的，训练集和验证集作为训练样本。你们在验证集上测试当然会和我的结果有出入 @Smoothing97 @pangzhan27 @czzbb @clw5180 
另外由于我上传错了权重，它测出来的并不是我报的结果，会差一点，所以建议自己做训练一下。

**Comment by pangzhan27** [comment]
明白了。谢谢

**Comment by clw5180** [comment]
> 明白了。谢谢

请教下你的anchor scale和ratio是采用默认值么？就是
ANCHOR_SCALES = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0] 
ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3.,  1 / 4., 4., 5., 1 / 5., 6., 1 / 6., 7., 1 / 7.]

**Comment by clw5180** [comment]
> @clw5180
> I have retrained the model, and after about 9 epochs, i get map 58.4 after stiching on val_dataset, still a little lower than the reported one, yet closer. However, the author did not mention the metric of evaluation- whether it's on cropped images or original ones. If it's based on "DOTA: A Larger-scale Dataset for Object Detection in Aerial Images", the results would be on original images, which would make sense according to the re-implemented results.

我使用的是官网的测评脚本，测试的是原图，不是crop后的；我再跑一次试试吧。

**Comment by clw5180** [comment]
> 我列出来的结果是测试集的，通过提交系统得到的，训练集和验证集作为训练样本。你们在验证集上测试当然会和我的结果有出入 @Smoothing97 @pangzhan27 @czzbb @clw5180
> 另外由于我上传错了权重，它测出来的并不是我报的结果，会差一点，所以建议自己做训练一下。

另外想请教yangxue大佬一个问题，EAST能否用于遥感图像的目标检测？只是检测 @yangxue0827

**Comment by yangxue0827** [comment]
当然可以，只不过你需要修改成多类检测 @clw5180

**Comment by choimroc** [comment]
@yangxue0827 您好！打扰了！我使用自己的数据集训练出了weights(迭代次数31W时的结果)，在使用demo.py和demo_rh.py进行测试时，发现score非常低，基本都在0.05以下，但是在train过程中的score是非常高的，基本是在0.8以上；通过阅读代码发现demo.py在使用build_whole_detection_network得到结果后还会再使用tf.session来计算得出结果，而train时是直接使用build_whole_detection_network的结果，不知道是在哪个环节出了问题?

**Comment by baokelion** [comment]
> > 明白了。谢谢
> 
> 请教下你的anchor scale和ratio是采用默认值么？就是
> ANCHOR_SCALES = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0]
> ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3., 1 / 4., 4., 5., 1 / 5., 6., 1 / 6., 7., 1 / 7.]
> 还有其它的参数也是和作者一样，没有修改就可以达到0.5+的mAP？

请问您后来修改参数了吗？我使用默认参数进行测试，效果不理想，不知道是否是参数的问题

**Comment by clw5180** [comment]
> > > 明白了。谢谢
> > 
> > 
> > 请教下你的anchor scale和ratio是采用默认值么？就是
> > ANCHOR_SCALES = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0]
> > ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3., 1 / 4., 4., 5., 1 / 5., 6., 1 / 6., 7., 1 / 7.]
> > 还有其它的参数也是和作者一样，没有修改就可以达到0.5+的mAP？
> 
> 请问您后来修改参数了吗？我使用默认参数进行测试，效果不理想，不知道是否是参数的问题

一样，你是做2019遥感图像检测比赛的么？我用这个模型只能达到0.23左右，DOTA的验证集0.51。

**Comment by baokelion** [comment]
> > > > 明白了。谢谢
> > > 
> > > 
> > > 请教下你的anchor scale和ratio是采用默认值么？就是
> > > ANCHOR_SCALES = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0]
> > > ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3., 1 / 4., 4., 5., 1 / 5., 6., 1 / 6., 7., 1 / 7.]
> > > 还有其它的参数也是和作者一样，没有修改就可以达到0.5+的mAP？
> > 
> > 
> > 请问您后来修改参数了吗？我使用默认参数进行测试，效果不理想，不知道是否是参数的问题
> 
> 一样，你是做2019遥感图像检测比赛的么？我用这个模型只能达到0.23左右，DOTA的验证集0.51。

是的，我是裁剪之后的图片进行测试，但是eval.py似乎有问题，map为0，我不知道是因为裁剪图片的问题还是我哪里设置错误了

**Comment by clw5180** [comment]
> > > > > 明白了。谢谢
> > > > 
> > > > 
> > > > 请教下你的anchor scale和ratio是采用默认值么？就是
> > > > ANCHOR_SCALES = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0]
> > > > ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3., 1 / 4., 4., 5., 1 / 5., 6., 1 / 6., 7., 1 / 7.]
> > > > 还有其它的参数也是和作者一样，没有修改就可以达到0.5+的mAP？
> > > 
> > > 
> > > 请问您后来修改参数了吗？我使用默认参数进行测试，效果不理想，不知道是否是参数的问题
> > 
> > 
> > 一样，你是做2019遥感图像检测比赛的么？我用这个模型只能达到0.23左右，DOTA的验证集0.51。
> 
> 是的，我是裁剪之后的图片进行测试，但是eval.py似乎有问题，map为0，我不知道是因为裁剪图片的问题还是我哪里设置错误了

可以用DOTA官网的测评脚本

**Comment by baokelion** [comment]
> > > > > > 明白了。谢谢
> > > > > 
> > > > > 
> > > > > 请教下你的anchor scale和ratio是采用默认值么？就是
> > > > > ANCHOR_SCALES = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0]
> > > > > ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3., 1 / 4., 4., 5., 1 / 5., 6., 1 / 6., 7., 1 / 7.]
> > > > > 还有其它的参数也是和作者一样，没有修改就可以达到0.5+的mAP？
> > > > 
> > > > 
> > > > 请问您后来修改参数了吗？我使用默认参数进行测试，效果不理想，不知道是否是参数的问题
> > > 
> > > 
> > > 一样，你是做2019遥感图像检测比赛的么？我用这个模型只能达到0.23左右，DOTA的验证集0.51。
> > 
> > 
> > 是的，我是裁剪之后的图片进行测试，但是eval.py似乎有问题，map为0，我不知道是因为裁剪图片的问题还是我哪里设置错误了
> 
> 可以用DOTA官网的测评脚本

如果使用dota官网的测评的话，是不是还是需要先用eval.py生成检测结果文件

**Comment by clw5180** [comment]
> > > > > > > 明白了。谢谢
> > > > > > 
> > > > > > 
> > > > > > 请教下你的anchor scale和ratio是采用默认值么？就是
> > > > > > ANCHOR_SCALES = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0]
> > > > > > ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3., 1 / 4., 4., 5., 1 / 5., 6., 1 / 6., 7., 1 / 7.]
> > > > > > 还有其它的参数也是和作者一样，没有修改就可以达到0.5+的mAP？
> > > > > 
> > > > > 
> > > > > 请问您后来修改参数了吗？我使用默认参数进行测试，效果不理想，不知道是否是参数的问题
> > > > 
> > > > 
> > > > 一样，你是做2019遥感图像检测比赛的么？我用这个模型只能达到0.23左右，DOTA的验证集0.51。
> > > 
> > > 
> > > 是的，我是裁剪之后的图片进行测试，但是eval.py似乎有问题，map为0，我不知道是因为裁剪图片的问题还是我哪里设置错误了
> > 
> > 
> > 可以用DOTA官网的测评脚本
> 
> 如果使用dota官网的测评的话，是不是还是需要先用eval.py生成检测结果文件

用的原图。不需要eval.py，直接用demo_rh预测出18类的txt就可以了，你仔细看一下测评脚本的代码。另外作者的demo_rh好像有点问题，测试阶段没有resize，我参考作者的RetinaNet_Rotation改了一下，不过resize的结果一般，不如直接用crop的尺寸就行。

**Comment by baokelion** [comment]
> > > > > > > > 明白了。谢谢
> > > > > > > 
> > > > > > > 
> > > > > > > 请教下你的anchor scale和ratio是采用默认值么？就是
> > > > > > > ANCHOR_SCALES = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0]
> > > > > > > ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3., 1 / 4., 4., 5., 1 / 5., 6., 1 / 6., 7., 1 / 7.]
> > > > > > > 还有其它的参数也是和作者一样，没有修改就可以达到0.5+的mAP？
> > > > > > 
> > > > > > 
> > > > > > 请问您后来修改参数了吗？我使用默认参数进行测试，效果不理想，不知道是否是参数的问题
> > > > > 
> > > > > 
> > > > > 一样，你是做2019遥感图像检测比赛的么？我用这个模型只能达到0.23左右，DOTA的验证集0.51。
> > > > 
> > > > 
> > > > 是的，我是裁剪之后的图片进行测试，但是eval.py似乎有问题，map为0，我不知道是因为裁剪图片的问题还是我哪里设置错误了
> > > 
> > > 
> > > 可以用DOTA官网的测评脚本
> > 
> > 
> > 如果使用dota官网的测评的话，是不是还是需要先用eval.py生成检测结果文件
> 
> 用的原图。不需要eval.py，直接用demo_rh预测出18类的txt就可以了，你仔细看一下测评脚本的代码。另外作者的demo_rh好像有点问题，测试阶段没有resize，我参考作者的RetinaNet_Rotation改了一下，不过resize的结果一般，不如直接用crop的尺寸就行。

好的，非常感谢！

**Comment by baokelion** [comment]
> > > > > > > > 明白了。谢谢
> > > > > > > 
> > > > > > > 
> > > > > > > 请教下你的anchor scale和ratio是采用默认值么？就是
> > > > > > > ANCHOR_SCALES = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0]
> > > > > > > ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3., 1 / 4., 4., 5., 1 / 5., 6., 1 / 6., 7., 1 / 7.]
> > > > > > > 还有其它的参数也是和作者一样，没有修改就可以达到0.5+的mAP？
> > > > > > 
> > > > > > 
> > > > > > 请问您后来修改参数了吗？我使用默认参数进行测试，效果不理想，不知道是否是参数的问题
> > > > > 
> > > > > 
> > > > > 一样，你是做2019遥感图像检测比赛的么？我用这个模型只能达到0.23左右，DOTA的验证集0.51。
> > > > 
> > > > 
> > > > 是的，我是裁剪之后的图片进行测试，但是eval.py似乎有问题，map为0，我不知道是因为裁剪图片的问题还是我哪里设置错误了
> > > 
> > > 
> > > 可以用DOTA官网的测评脚本
> > 
> > 
> > 如果使用dota官网的测评的话，是不是还是需要先用eval.py生成检测结果文件
> 
> 用的原图。不需要eval.py，直接用demo_rh预测出18类的txt就可以了，你仔细看一下测评脚本的代码。另外作者的demo_rh好像有点问题，测试阶段没有resize，我参考作者的RetinaNet_Rotation改了一下，不过resize的结果一般，不如直接用crop的尺寸就行。

你好，我使用了demo_rh，但是并没有得到分类的txt文件，需要修改哪里吗？

**Comment by baokelion** [comment]
> > > > > > > > 明白了。谢谢
> > > > > > > 
> > > > > > > 
> > > > > > > 请教下你的anchor scale和ratio是采用默认值么？就是
> > > > > > > ANCHOR_SCALES = [0.0625, 0.125, 0.25, 0.5, 1.0, 2.0]
> > > > > > > ANCHOR_RATIOS = [1, 1 / 2, 2., 1 / 3., 3., 1 / 4., 4., 5., 1 / 5., 6., 1 / 6., 7., 1 / 7.]
> > > > > > > 还有其它的参数也是和作者一样，没有修改就可以达到0.5+的mAP？
> > > > > > 
> > > > > > 
> > > > > > 请问您后来修改参数了吗？我使用默认参数进行测试，效果不理想，不知道是否是参数的问题
> > > > > 
> > > > > 
> > > > > 一样，你是做2019遥感图像检测比赛的么？我用这个模型只能达到0.23左右，DOTA的验证集0.51。
> > > > 
> > > > 
> > > > 是的，我是裁剪之后的图片进行测试，但是eval.py似乎有问题，map为0，我不知道是因为裁剪图片的问题还是我哪里设置错误了
> > > 
> > > 
> > > 可以用DOTA官网的测评脚本
> > 
> > 
> > 如果使用dota官网的测评的话，是不是还是需要先用eval.py生成检测结果文件
> 
> 用的原图。不需要eval.py，直接用demo_rh预测出18类的txt就可以了，你仔细看一下测评脚本的代码。另外作者的demo_rh好像有点问题，测试阶段没有resize，我参考作者的RetinaNet_Rotation改了一下，不过resize的结果一般，不如直接用crop的尺寸就行。

打扰了，请问train.py进行训练的时候，有sess.run()挂起卡住的问题吗？

**Comment by yangxue0827** [comment]
检查tfrecord是否有数据 @baokelion
