### ISSUE TITLE
cannot create weak reference to 'builtin_function_or_method' object

### ISSUE THREAD

**Issue by ZhangHe95** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#63]
请问跑demo的时候报：
File "/home/xxx/anaconda3/envs/py27-env/lib/python2.7/weakref.py", line 311, in __new__
    self = ref.__new__(type, ob, callback)
TypeError: cannot create weak reference to 'builtin_function_or_method' object
是哪里出问题了呢

**Comment by Smoothing97** [comment]
没有详细看，报错显示是配置的环境出了问题吗？

**Comment by GGBond18** [comment]
请问解决了吗？

**Comment by ZhangHe95** [comment]
谢谢解决了！




------------------ 原始邮件 ------------------
发件人: "GGBond18"<notifications@github.com>;
发送时间: 2019年7月16日(星期二) 晚上7:55
收件人: "DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow"<R2CNN_Faster-RCNN_Tensorflow@noreply.github.com>;
抄送: "张訸"<963247314@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow] cannot createweak reference to 'builtin_function_or_method' object (#63)




请问解决了吗？
