### ISSUE TITLE
水平框中FPN的参数设置

### ISSUE THREAD

**Issue by summerrr** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#65]
水平框目标检测中，看你的FPN跑完结果能达到72%，请问你是怎么设置的参数，我跑完结果只能达到62%

**Comment by yangxue0827** [comment]
你可以问下[这里](https://github.com/DetectionTeamUCAS/FPN_Tensorflow/issues/59)，我没有直接用FPN跑dota。 @summerrr
