### ISSUE TITLE
How to unzip the trained weights?

### ISSUE THREAD

**Issue by ZhangGongjie** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#7]
How to unzip the trained weights?

**Comment by yangxue0827** [comment]
you can unzip it on windows.

**Comment by banderlog** [comment]
Or with 7zip (do not forget to install `p7zip-full` and `p7zip-rar`):  
`7z x  FasterRCNN_20180515_DOTA_v3.part1.rar`
