### ISSUE TITLE
训练时过程中出错

### ISSUE THREAD

**Issue by dexterod** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#70]
大兄弟啊，我按你的流程一步步走下来，在运行最后一个train.py的时候出现了错误，这个错误出现的时间还是随机的，有时候是成功训练了几十张、有时候是成功训练了一百多张DOTA图片的时候突然出现error：
OutOfRangeError (see above for traceback): PaddingFIFOQueue '_1_batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0) 
[[node batch (defined at /media/S318080208/py_files/R2CNN_Faster-RCNN_Tensorflow-master/data/io/read_tfrecord.py:98)  = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch/padding_fifo_queue, batch/n)]]

我把你的那个read_tfrecord里的tf.train.batch中的capacity、num_threads都往大了设置，可是也没用...

大佬你遇没遇到过这个问题啊...

**Comment by sunshinezhihuo** [comment]
我也遇到了同样的问题

**Comment by yangxue0827** [comment]
检查tfrecord，PaddingFIFOQueue问题基本是读不出数据造成的。 @dexterod @sunshinezhihuo
