### ISSUE TITLE
Using pretrained weights for training on 3 categories

### ISSUE THREAD

**Issue by deimsdeutsch** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#71]
Hi,

When i tried using it on pretrained weights by settings the number of classes to 3 i got an error. 
Assign requires shapes of both tensors to match. lhs shape= [16] rhs shape= [64]

Should i train from scratch ?

Thanks.

**Comment by mdv3101** [comment]
Yes.

**Comment by yangxue0827** [comment]
No, it should be caused by some parameters not modified. @deimsdeutsch
