### ISSUE TITLE
why just support batch_size = 1 in training ?

### ISSUE THREAD

**Issue by clw5180** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#73]
I have cropped the training dataset and got ~100000 images, and I only have one GPU. It's about 1 day to train 1 epoch, so how to deal with this problem? Do I have to train for half a month?

**Comment by yangxue0827** [comment]
I have only 2w images (800 * 800 size, 200 overlap). @

**Comment by clw5180** [comment]
> I have only 2w images (800 * 800 size, 200 overlap).

Recently I joined a competition about object detection in remote sensing objects , and I found that DOTA is just a small subset of that dataset......
