### ISSUE TITLE
FYI : Both train_crop.py and val_crop.py are generating wrong coordinates!

### ISSUE THREAD

**Issue by dexception** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#74]
FYI:
After you tag your images using labelme you run these scripts:
train_crop.py
val_crop.py

So the coordinates generated after chopping the images are wrong and in some cases totally wrong.
Don't rely on this and write your own code for generating cropped images.

**Comment by yangxue0827** [comment]
These scripts aee for DOTA dataset. @dexception

**Comment by clw5180** [comment]
> FYI:
> After you tag your images using labelme you run these scripts:
> train_crop.py
> val_crop.py
> 
> So the coordinates generated after chopping the images are wrong and in some cases totally wrong.
> Don't rely on this and write your own code for generating cropped images.

Does a part of the box outside the image boundary need to be removed? Can you share your code?
请问某一部分在图片边界之外的框是否需要舍掉？能否分享下你的代码?（框的坐标换算我感觉没啥问题吧？只不过对于在边界之外的框没有舍弃）

**Comment by dexception** [comment]
@yangxue0827 @clw5180 
The code is not robust enough to used for any dataset.
- It will generated negative coordinates
- Also it will randomly mark anything as an object
- Also it will split the object in half
- It will include images that do not even have any objects

So it is better to write these scripts yourself rather than use the ones provided with the repo.

**Comment by yangxue0827** [comment]
边界框是通过判断中心点是否在图里来保留的也就是iou大于0.5。 @clw5180

**Comment by yangxue0827** [comment]
兄弟，你能提供这些情况的可视化图例吗，我用这个完全没问题，出了一个目标被裁剪成两部分这个没办法解决，其他的都没有遇到过。 @dexception

**Comment by dexception** [comment]
@yangxue0827 
I cannot share the images. 
You can trust me on this that this is definitely an issue.

**Comment by clw5180** [comment]
> 边界框是通过判断中心点是否在图里来保留的也就是iou大于0.5。 @clw5180

got it, thanks !

**Comment by clw5180** [comment]
> @yangxue0827
> I cannot share the images.
> You can trust me on this that this is definitely an issue.

这个没有问题，你可以再试试
