### ISSUE TITLE
demo_rh.py 耗时

### ISSUE THREAD

**Issue by czzbb** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#76]
一共458张val，跑demo_rh.py一般都要多久啊，我跑的好慢，大概二三十秒一张图，这个正常吗

**Comment by yangxue0827** [comment]
这个repo的DOTA代码比较慢，之后我会上传一个[RetinaNet_for_DOTA_Tensorflow](https://github.com/DetectionTeamUCAS/RetinaNet_for_DOTA_Tensorflow)的代码，评测使用多gpu，速度很快，效果也不错。 @czzbb 
你可以先参考下面这个脚本，可能需要改一下，不能直接跑。
[test_dota.txt](https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow/files/3397562/test_dota.txt)

**Comment by czzbb** [comment]
十分感谢！
