### ISSUE TITLE
demo_rh.py中 cfgs.SHOW_SCORE_THRSHOLD 和r_threshold/h_threshold

### ISSUE THREAD

**Issue by czzbb** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#78]
请问下：
1. 为什么提交结果时cfgs.SHOW_SCORE_THRSHOLD 中的值要那么小，这样不是网络预测出的score很小都被当作目标了吗（虽然值为0.001的结果确实比0.5的结果好挺多），我想知道为什么？
2. 175行r_threshold和180行h_threshold的值是怎么得到的

**Comment by yangxue0827** [comment]
你要先理解一下什么是mAP @czzbb

**Comment by czzbb** [comment]
噢噢噢明白了！谢谢您，那第二个问题呢，不同类别的IOU是怎么得到的

**Comment by yangxue0827** [comment]
阈值是靠调参选出来的较优值 @czzbb

**Comment by czzbb** [comment]
好的，十分感谢您！
