### ISSUE TITLE
请教一下postprocess_rpn_proposals()代码实现的一个问题

### ISSUE THREAD

**Issue by clw5180** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#79]
里面的clip_boxes_to_img_boundaries方法，我看在Faster RCNN论文中是测试阶段才使用，而训练阶段会无视所有超出边界的anchor（ignore all cross-boundary anchors, and they will not contribute to the loss.），但代码中似乎训练和测试阶段都保留了超出边界的anchor并且都截取到边界clip_boxes_to_img_boundaries，这个对最终的性能是否会有影响？

**Comment by yangxue0827** [comment]
我记得Faster rcnn原论文是要过滤，FPN不过滤吧，不太记得了，应该影响不大的。 @clw5180
