### ISSUE TITLE
About accuracy

### ISSUE THREAD

**Issue by auroua** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#8]
I have read the code in this repo and I found  this code doesn't contain the `DFPN`, `FPN`, `Adaptive ROI Align` parts.
I find the code is a standard `faster rcnn` with a `obb loss` branch in `Fast-RCNN` part. Does this code can get about `60.x map` on `dota` dataset? 
Did you trained the model with inputs that is cropped from original images with `800*800` pixels and cropped overlaps is `200` pixeles?

**Comment by yangxue0827** [comment]
This repo is just based on Faster-RCNN and does not include DFPN, FPN, Adaptive ROI Align. In addition, we trained the model with inputs that is cropped from original images with 800*800 pixels and cropped overlaps is 200 pixeles, and achieve 60.x map. 
We have now obtained a 67+ map by improving this repo.
