### ISSUE TITLE
无预测结果

### ISSUE THREAD

**Issue by peterkobe** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#83]
您好，在用您给的程序训练自己的数据集时（只有一个类别标签），训练集预测结果如图所示
![Screenshot from 2019-07-29 16-47-07](https://user-images.githubusercontent.com/53441311/62062748-86fe7a00-b221-11e9-9ac8-6e487c04998d.png)
![Screenshot from 2019-07-29 16-47-25](https://user-images.githubusercontent.com/53441311/62062755-8960d400-b221-11e9-8466-d2a7ee90e85c.png)
另外训练过程中fast_rcnn的各项ｌｏｓｓ值均为０
![Screenshot from 2019-07-29 16-47-49](https://user-images.githubusercontent.com/53441311/62062883-c9c05200-b221-11e9-8be0-a5e9752b5e14.png)　请问是什么原因？万分感谢

**Comment by yangxue0827** [comment]
你看gt那部分就显示的不对，你的数据标签有问题 @peterkobe

**Comment by peterkobe** [comment]
已解决，ｔｆ文件生成的有问题重新ｄｅｂｕｇ了一遍，感谢
