### ISSUE TITLE
关于weights保存的问题

### ISSUE THREAD

**Issue by choimroc** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#84]
您好！非常感谢您的project！

我发现在迭代过程中，保存的weights会自动删除，只会保留近几次保存的weights。我向请问这个自动删除的机制是什么呢？是会自动select最优效果的weights吗？还是只是顺序删除呢？

感谢！

**Comment by yangxue0827** [comment]
顺序删除，参数在train脚本中可以设置 @choimroc

**Comment by choimroc** [comment]
好的，感谢！@yangxue0827
