### ISSUE TITLE
请问是不是 cfgs.PIXEL_MEAN 写错了？

### ISSUE THREAD

**Issue by ForeverStrongCheng** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#85]
**请问是不是 cfgs.PIXEL_MEAN 写错了？**

1. 75 行：https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow/blob/master/tools/camera_demo.py

```
feed_dict={img_plac: frame}
```

OpenCV 读入数据，frame 应为 BGR 格式。

2. 40 行：https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow/blob/master/tools/camera_demo.py

```
    img_batch = img_batch - tf.constant(cfgs.PIXEL_MEAN)
```

然而 libs/configs/cfgs*.py 中 cfgs.PIXEL_MEAN 则是 R, G, B.

3. 65 行：https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow/blob/master/libs/configs/cfgs_FDDB_mobilenet_v1.py

```
PIXEL_MEAN = [123.68, 116.779, 103.939]  # R, G, B. In tf, channel is RGB. In openCV, channel is BGR
```

@yangxue0827

**Comment by yangxue0827** [comment]
这个脚本可能是写错了，谢谢提醒。其他的脚本应该没错
![image](https://user-images.githubusercontent.com/29257168/67951132-e22b7880-fc25-11e9-8211-6a6db6287d61.png)
@ForeverStrongCheng

**Comment by ForeverStrongCheng** [comment]
Thank you for your reply.
