### ISSUE TITLE
voc_eval.py error     print("cls : {}|| Recall: {} || Precison: {}|| AP: {}".format(cls, recall[-1], precision[-1], AP))

### ISSUE THREAD

**Issue by baokelion** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#86]
我在使用eval.py对dota裁剪的val数据集进行评估出错，  第277行
print("cls : {}|| Recall: {} || Precison: {}|| AP: {}".format(cls, recall[-1], precision[-1], AP))
IndexError: index -1 is out of bounds for axis 0 with size 0
请问是我使用的dota数据集出错的原因还是其他原因？

**Comment by yangxue0827** [comment]
建议用官方评估的脚本 @baokelion

**Comment by baokelion** [comment]
> 建议用官方评估的脚本 @baokelion

好的，谢谢，那该如何生成官方评估需要的txt文件呢

**Comment by yangxue0827** [comment]
demo_rh.py @baokelion
