### ISSUE TITLE
使用训练好的模型测试效果不好

### ISSUE THREAD

**Issue by baokelion** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#87]

**Comment by pureyangcry** [comment]
me too,and I also don't know how to train my dataset to detect object,including create datasets and labels, is there have some tools? who can help me? thanks

**Comment by baokelion** [comment]
@pureyangcry  You can use the tools in data/io that Introduced in readme.I suggest you view the source code.

**Comment by pureyangcry** [comment]
> @pureyangcry You can use the tools in data/io that Introduced in readme.I suggest you view the source code.

ok, thank you, I will view it, but I want to ask a question is very stupid, is there have some tools like labelImg to make label?

**Comment by pureyangcry** [comment]
> @pureyangcry You can use the tools in data/io that Introduced in readme.I suggest you view the source code.

ok, thank you, I will view it, but I want to ask a question is very stupid, is there have some tools like labelImg to make label?

**Comment by pureyangcry** [comment]
> @pureyangcry You can use the tools in data/io that Introduced in readme.I suggest you view the source code.
ok, thank you, I will view it, but I want to ask a question is very stupid, is there have some tools like labelImg to make label?

**Comment by baokelion** [comment]
@pureyangcry Sorry, I only know the conversion of the label format, I don’t know how to make the label.

**Comment by pureyangcry** [comment]
> @baokelion 

ok, thank you

**Comment by TheToadAlly** [comment]
You can use Dota or ICDAR datasets which are already annotated. 

You dataset then needs to be serialiazed to TFRecords format.  The script "convert_data_to_tfrecords" expects your data to be in pascal VOC format I believe.The script "train_crop.py" in io/DOTA folder both crops your images into smaller tiles as well as converts text file DOTA annotations to xml format.

**Comment by pureyangcry** [comment]
@TheToadAlly 

yes, thank you ! I have got the data from Dota, but it's not very userful for me? I have to find how to annotate my own data ,you konw, the object I wanto to detect is different from Dota. In all, thanks,I get a idea use LabelMe tool to annotate and then converte to the needed format of the model(just a idea, I will try)

**Comment by pureyangcry** [comment]
@baokelion  
hi,man! I have got it, and it's training. I use LabelMe to annotate my own dataset. the format of label is json, so I use some python codes to converse it to the needed format(x0,y0,x1...y3).so I generate the tfrecoed files.  the result I test as follow.
![result](https://user-images.githubusercontent.com/13905121/63156241-d8db3880-c046-11e9-8acd-49f5a8f91c69.jpg)
