### ISSUE TITLE
训练停留在sess.run(([global_step, img_name_batch, rpn_location_loss, rpn_cls_loss,....)

### ISSUE THREAD

**Issue by yc12138** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#89]
训练一直停滞在restore model后，测试了下发现train程序一直在sess.run()不进行下一步，测试demo程序等其它程序时都是ok的，请问是什么问题？有什么解决的方法，谢谢

**Comment by yangxue0827** [comment]
tfrecord没数据，生成有问题 @yc12138

**Comment by yc12138** [comment]
> 
> 
> tfrecord没数据，生成有问题 @yc12138

谢谢，已经解决

**Comment by FortuneStar** [comment]
我也出现这个问题了，是我生成的tfrecord的问题吗，但是我生成过程中并未出现问题。

**Comment by FortuneStar** [comment]
> tfrecord没数据，生成有问题 @yc12138

我也出现这个问题了，是我生成的tfrecord的问题吗，但是我生成过程中并未出现问题。
