### ISSUE TITLE
rotate_gpu_nms 

### ISSUE THREAD

**Issue by auroua** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#9]
I can't find model `rotate_gpu_nms.py`  in `bbx_utils` package. Could you upload this model? Thanks~

**Comment by ZekunZh** [comment]
Same problem as you @auroua . I think the ``rotate_gpu_nms`` is a complied lib instead of ``.py`` 

And ``rotate_polygon_nms`` is also missing in ``box_utils``.

Could you @yangxue0827  @yangJirui  help us ? Thanks !

**Comment by yangxue0827** [comment]
whole project has been uploaded. @auroua @ZekunZh

**Comment by haibucuo0** [comment]
> I can't find model `rotate_gpu_nms.py` in `bbx_utils` package. Could you upload this model? Thanks~

Hi,have you solved it?I got the same problem.
