### ISSUE TITLE
how to generate PB file

### ISSUE THREAD

**Issue by pureyangcry** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#91]
I use ./lib/export_pbs to generate PB file, but It not work. the error as follow :
    ValueError: Shape must be rank 4 but is rank 5 for 'resnet_v1_101/Pad' (op: 'Pad') with input shapes: [1,1,?,?,3], [4,2].
can you tell me? how can  I get  the PB file, Thanks @yangxue0827

**Comment by yangxue0827** [comment]
This part is written in the Faster RCNN code. If you want to use it in this repo, you need to modify it because this is rotation detection. You need to read the code first and find that the place to be modified is not difficult. @pureyangcry

**Comment by pureyangcry** [comment]
ok, I'm working for it.

**Comment by cherish24** [comment]
你好，最后是怎么解决的，能共享吗
