### ISSUE TITLE
batchsize

### ISSUE THREAD

**Issue by lijain** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#92]
how to change batchsize,not only bachsize equal one

**Comment by yangxue0827** [comment]
only support batchsize=1 @lijain

**Comment by lijain** [comment]
Yes, I mean, can you modify the network to make it more than 1? Bachsize can be set to any value to be modified? 





------------------ 原始邮件 ------------------
发件人: "yangxue"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 上午9:34
收件人: "DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow"<R2CNN_Faster-RCNN_Tensorflow@noreply.github.com>;
抄送: "利剑"<1632401541@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow] batchsize (#92)




only support batchsize=1 @lijain

**Comment by yangxue0827** [comment]
This may require a lot of changes, I recommend you use multi-gpu training. Reference script: https://github.com/DetectionTeamUCAS/NAS_FPN_Tensorflow/blob/master/tools/multi_gpu_train.py @lijain

**Comment by lijain** [comment]
Okay, let me see. Thank you

------------------ 原始邮件 ------------------
发件人: "yangxue"<notifications@github.com>;
发送时间: 2019年8月29日(星期四) 上午9:44
收件人: "DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow"<R2CNN_Faster-RCNN_Tensorflow@noreply.github.com>;
抄送: "利剑"<1632401541@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow] batchsize (#92)




This may require a lot of changes, I recommend you use multi-gpu training. Reference script: https://github.com/DetectionTeamUCAS/NAS_FPN_Tensorflow/blob/master/tools/multi_gpu_train.py @lijain

**Comment by lijain** [comment]
Let me see if the multi_gpu_train (fast_rcnn. build_whole_detection_network) network has one less parameter.

**Comment by mohanaditya910** [comment]
I am planning to implement batchsize>1..can @yangxue0827 suggest me where to start?

Thank you.
