### ISSUE TITLE
about the shape of  output Image

### ISSUE THREAD

**Issue by pureyangcry** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#93]
Why the shape of the image I input is (500,300), but after testing the shape of output result is (1000,800), I resize the shape to (2000,1200), and the image shape output is still (1000,800). why the shape of input and output different? how can I the same shape between input and  output? Thanks!

**Comment by yangxue0827** [comment]
The code will fix the short side of image to [800](https://github.com/DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow/blob/master/libs/configs/cfgs.py#L66). 
@pureyangcry
