### ISSUE TITLE
multi_gpu_train

### ISSUE THREAD

**Issue by lijain** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#94]
run multi_gpu_train。When the parameters are supplemented, they will be supplemented. What are the following problems in operation? 
ValueError: Variable resnet_v1_101/block3/unit_1/bottleneck_v1/shortcut/weights/Momentum/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?
Baidu has no results. How do you solve the problem in this. py file? Thank you

**Comment by yangxue0827** [comment]
Try [multi_gpu_train.py](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/tools/multi_gpu_train.py), but you need do some modify first. @lijain
