### ISSUE TITLE
Bad result for horizontal/vertical object

### ISSUE THREAD

**Issue by vudq** [DetectionTeamUCAS/R2CNN_Faster-RCNN_Tensorflow#97]
Hi, thanks for sharing your great work!
I'm trying to use your model in text object detection. It predict very well for inclined object.
However, With horizontal/vertical Object, the rotated box is bad as you can see images below
Horizontal Object : https://drive.google.com/open?id=18yNNqqpmAEg6CAyqmXRGzvthAFpqOeFp
Vertical Object : https://drive.google.com/open?id=1M2PGxyXaBeYwgIPLv71w9veh0rfbCNrd

Any suggestion on fixing this?

Best,
Vu

**Comment by yangxue0827** [comment]
This is exactly what I solved in my ICCV2019 paper. Please read IoU Smooth L1 in [SCRDet](https://arxiv.org/abs/1811.07126) for specific questions. The relevant [code ](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation)is [here](https://github.com/DetectionTeamUCAS/RetinaNet_Tensorflow_Rotation/blob/master/libs/losses/losses.py#L171).
@vudq

**Comment by vudq** [comment]
Thanks for your quick reply. So it is possible to use your new loss function( iou_smooth_l1_loss) in this project?

**Comment by yangxue0827** [comment]
You need to add it yourself. @vudq
